package op

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/bestruirui/octopus/internal/db"
	"github.com/bestruirui/octopus/internal/model"
	"github.com/bestruirui/octopus/internal/utils/xstrings"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type groupAutoGenerateCandidate struct {
	ModelName string
	ChannelID int
}

type groupAutoGenerateModelBucket struct {
	ModelName          string
	Aliases            []string
	Candidates         []groupAutoGenerateCandidate
	MatchScore         int
	MatchStrategies    []string
	preferredNameScore int
	scoreTotal         int
	scoreCount         int
}

type groupAutoGenerateOptions struct {
	AssociationMode      model.GroupAutoGenerateAssociationMode
	StripProviderPrefix  bool
	StripModelsNamespace bool
	NormalizeCase        bool
	NormalizeSeparators  bool
	ManualAliases        map[string]string
}

func GroupAutoGeneratePreview(req *model.GroupAutoGenerateRequest, ctx context.Context) (*model.GroupAutoGeneratePreview, error) {
	options := groupAutoGenerateOptionsFromRequest(req)
	buckets, totalModels, err := groupAutoGenerateBuckets(req, ctx, options)
	if err != nil {
		return nil, err
	}
	groups, err := groupAutoGenerateExistingGroups(ctx, options)
	if err != nil {
		return nil, err
	}
	items := make([]model.GroupAutoGeneratePreviewItem, 0, len(buckets))
	for _, bucket := range buckets {
		items = append(items, groupAutoGeneratePreviewItem(bucket, groups[groupAutoGenerateModelKey(bucket.ModelName, options)], options))
	}
	return &model.GroupAutoGeneratePreview{
		TotalModels:     totalModels,
		SelectedModels:  len(items),
		AssociationMode: options.AssociationMode,
		Items:           items,
	}, nil
}

func GroupAutoGenerate(req *model.GroupAutoGenerateRequest, ctx context.Context) (*model.GroupAutoGenerateResult, error) {
	options := groupAutoGenerateOptionsFromRequest(req)
	buckets, totalModels, err := groupAutoGenerateBuckets(req, ctx, options)
	if err != nil {
		return nil, err
	}

	mode, firstTokenTimeout, sessionKeepTime, retryEnabled, maxRetries := groupAutoGenerateDefaults(req)
	result := &model.GroupAutoGenerateResult{
		TotalModels:     totalModels,
		SelectedModels:  len(buckets),
		AssociationMode: options.AssociationMode,
		Items:           make([]model.GroupAutoGenerateResultItem, 0, len(buckets)),
	}
	affectedChannelIDs := make([]int, 0)

	err = db.GetDB().WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		groups, err := groupAutoGenerateExistingGroupsWithDB(tx, options)
		if err != nil {
			return err
		}

		for _, bucket := range buckets {
			item := model.GroupAutoGenerateResultItem{
				ModelName:       bucket.ModelName,
				Aliases:         groupAutoGenerateAliasesForDisplay(bucket),
				CandidateCount:  len(bucket.Candidates),
				MatchScore:      bucket.MatchScore,
				MatchStrategies: groupAutoGenerateStrategyKeysForDisplay(bucket.MatchStrategies),
			}
			if len(bucket.Candidates) == 0 {
				item.SkippedReason = "no_candidates"
				result.SkippedGroups++
				result.Items = append(result.Items, item)
				continue
			}

			key := groupAutoGenerateModelKey(bucket.ModelName, options)
			existing := groups[key]
			if existing == nil {
				group := model.Group{
					Name:              bucket.ModelName,
					Mode:              mode,
					FirstTokenTimeOut: firstTokenTimeout,
					SessionKeepTime:   sessionKeepTime,
					RetryEnabled:      retryEnabled,
					MaxRetries:        maxRetries,
				}
				if err := tx.Create(&group).Error; err != nil {
					return fmt.Errorf("failed to create group %q: %w", bucket.ModelName, err)
				}
				created, err := groupAutoGenerateCreateItems(tx, group.ID, bucket.Candidates, 1)
				if err != nil {
					return err
				}
				item.GroupID = group.ID
				item.Created = true
				item.AddedItems = created
				result.CreatedGroups++
				result.AddedItems += created
				groups[key] = &model.Group{ID: group.ID, Name: group.Name, Items: nil}
				affectedChannelIDs = append(affectedChannelIDs, groupAutoGenerateCandidateChannelIDs(bucket.Candidates)...)
				result.Items = append(result.Items, item)
				continue
			}

			missing := groupAutoGenerateMissingCandidates(*existing, bucket.Candidates, options)
			item.GroupID = existing.ID
			if len(missing) == 0 {
				item.SkippedReason = "already_complete"
				result.SkippedGroups++
				result.Items = append(result.Items, item)
				continue
			}

			nextPriority := groupAutoGenerateNextPriority(existing.Items)
			created, err := groupAutoGenerateCreateItems(tx, existing.ID, missing, nextPriority)
			if err != nil {
				return err
			}
			item.AddedItems = created
			result.UpdatedGroups++
			result.AddedItems += created
			affectedChannelIDs = append(affectedChannelIDs, groupAutoGenerateCandidateChannelIDs(missing)...)
			result.Items = append(result.Items, item)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	if err := groupRefreshCache(ctx); err != nil {
		return nil, err
	}
	resetBalancerStateForChannels(affectedChannelIDs...)
	return result, nil
}

func groupAutoGenerateDefaults(req *model.GroupAutoGenerateRequest) (model.GroupMode, int, int, bool, int) {
	mode := model.GroupModeRoundRobin
	firstTokenTimeout := 0
	sessionKeepTime := 0
	retryEnabled := false
	maxRetries := 3
	if req == nil {
		return mode, firstTokenTimeout, sessionKeepTime, retryEnabled, maxRetries
	}
	if req.Mode != nil {
		switch *req.Mode {
		case model.GroupModeRoundRobin, model.GroupModeRandom, model.GroupModeFailover, model.GroupModeWeighted:
			mode = *req.Mode
		}
	}
	if req.FirstTokenTimeOut > 0 {
		firstTokenTimeout = req.FirstTokenTimeOut
	}
	if req.SessionKeepTime > 0 {
		sessionKeepTime = req.SessionKeepTime
	}
	retryEnabled = req.RetryEnabled
	if req.MaxRetries > 0 {
		maxRetries = req.MaxRetries
	}
	return mode, firstTokenTimeout, sessionKeepTime, retryEnabled, maxRetries
}

func groupAutoGenerateOptionsFromRequest(req *model.GroupAutoGenerateRequest) groupAutoGenerateOptions {
	options := groupAutoGenerateOptions{AssociationMode: model.GroupAutoGenerateAssociationExact}
	if req != nil && req.AssociationMode == model.GroupAutoGenerateAssociationAlias {
		options.AssociationMode = model.GroupAutoGenerateAssociationAlias
	}
	defaults := groupAutoGenerateDefaultAssociationOptions(options.AssociationMode)
	options.StripProviderPrefix = defaults.StripProviderPrefix
	options.StripModelsNamespace = defaults.StripModelsNamespace
	options.NormalizeCase = defaults.NormalizeCase
	options.NormalizeSeparators = defaults.NormalizeSeparators
	if req != nil && req.AssociationOptions != nil {
		if req.AssociationOptions.StripProviderPrefix != nil {
			options.StripProviderPrefix = *req.AssociationOptions.StripProviderPrefix
		}
		if req.AssociationOptions.StripModelsNamespace != nil {
			options.StripModelsNamespace = *req.AssociationOptions.StripModelsNamespace
		}
		if req.AssociationOptions.NormalizeCase != nil {
			options.NormalizeCase = *req.AssociationOptions.NormalizeCase
		}
		if req.AssociationOptions.NormalizeSeparators != nil {
			options.NormalizeSeparators = *req.AssociationOptions.NormalizeSeparators
		}
	}
	options.ManualAliases = groupAutoGenerateManualAliasMap(req, options)
	return options
}

func groupAutoGenerateDefaultAssociationOptions(mode model.GroupAutoGenerateAssociationMode) groupAutoGenerateOptions {
	options := groupAutoGenerateOptions{
		AssociationMode:      mode,
		NormalizeCase:        true,
		NormalizeSeparators:  false,
		StripModelsNamespace: false,
		StripProviderPrefix:  false,
	}
	if mode == model.GroupAutoGenerateAssociationAlias {
		options.NormalizeSeparators = true
		options.StripModelsNamespace = true
		options.StripProviderPrefix = true
	}
	return options
}

func groupAutoGenerateBuckets(req *model.GroupAutoGenerateRequest, ctx context.Context, options groupAutoGenerateOptions) ([]groupAutoGenerateModelBucket, int, error) {
	candidates, err := groupAutoGenerateCandidates(ctx, options)
	if err != nil {
		return nil, 0, err
	}
	allBuckets := groupAutoGenerateGroupCandidates(candidates, options)
	selected := groupAutoGenerateSelection(req, options)
	if len(selected) == 0 {
		return allBuckets, len(allBuckets), nil
	}
	result := make([]groupAutoGenerateModelBucket, 0, len(selected))
	for _, bucket := range allBuckets {
		if _, ok := selected[groupAutoGenerateModelKey(bucket.ModelName, options)]; ok {
			result = append(result, bucket)
		}
	}
	return result, len(allBuckets), nil
}

func groupAutoGenerateSelection(req *model.GroupAutoGenerateRequest, options groupAutoGenerateOptions) map[string]struct{} {
	if req == nil || req.All || len(req.ModelNames) == 0 {
		return nil
	}
	selected := make(map[string]struct{}, len(req.ModelNames))
	for _, name := range req.ModelNames {
		if key := groupAutoGenerateModelKey(name, options); key != "" {
			selected[key] = struct{}{}
		}
	}
	return selected
}

func groupAutoGenerateCandidates(ctx context.Context, options groupAutoGenerateOptions) ([]groupAutoGenerateCandidate, error) {
	var channels []model.Channel
	if err := db.GetDB().WithContext(ctx).Order("id ASC").Find(&channels).Error; err != nil {
		return nil, err
	}
	channelIDs := make([]int, 0, len(channels))
	for _, channel := range channels {
		channelIDs = append(channelIDs, channel.ID)
	}
	bindings, err := SiteChannelBindingMapByChannelIDs(channelIDs, ctx)
	if err != nil {
		return nil, err
	}

	result := make([]groupAutoGenerateCandidate, 0)
	for _, channel := range channels {
		if channel.ID == 0 || !channel.Enabled {
			continue
		}
		if binding, ok := bindings[channel.ID]; ok {
			modelNames, err := groupAutoGenerateProjectedModelNames(ctx, channel, binding)
			if err != nil {
				return nil, err
			}
			result = append(result, groupAutoGenerateCandidatesForChannel(channel.ID, modelNames, options)...)
			continue
		}
		modelNames := xstrings.SplitTrimCompact(",", channel.Model, channel.CustomModel)
		result = append(result, groupAutoGenerateCandidatesForChannel(channel.ID, modelNames, options)...)
	}
	return result, nil
}

func groupAutoGenerateProjectedModelNames(ctx context.Context, channel model.Channel, binding model.SiteChannelBinding) ([]string, error) {
	var rows []model.SiteModel
	if err := db.GetDB().WithContext(ctx).
		Where("site_account_id = ? AND disabled = ?", binding.SiteAccountID, false).
		Find(&rows).Error; err != nil {
		return nil, err
	}
	baseGroupKey, _ := model.ParseSiteChannelBindingKey(binding.GroupKey)
	routeType := model.SiteModelRouteTypeFromOutboundType(channel.Type)

	names := make([]string, 0, len(rows))
	for _, row := range rows {
		name := strings.TrimSpace(row.ModelName)
		if name == "" {
			continue
		}
		if model.NormalizeSiteGroupKey(row.GroupKey) != baseGroupKey {
			continue
		}
		if !groupAutoGenerateSiteModelBelongsToGroup(row, baseGroupKey) {
			continue
		}
		if model.NormalizeSiteModelRouteType(row.RouteType) != routeType {
			continue
		}
		names = append(names, name)
	}
	return names, nil
}

func groupAutoGenerateSiteModelBelongsToGroup(item model.SiteModel, groupKey string) bool {
	metadata, ok := model.ParseSiteModelRouteMetadata(item.RouteRawPayload)
	if !ok || len(metadata.EnableGroups) == 0 {
		return true
	}
	targetGroupKey := model.NormalizeSiteGroupKey(groupKey)
	for _, explicitGroupKey := range metadata.EnableGroups {
		if model.NormalizeSiteGroupKey(explicitGroupKey) == targetGroupKey {
			return true
		}
	}
	return false
}

func groupAutoGenerateCandidatesForChannel(channelID int, modelNames []string, options groupAutoGenerateOptions) []groupAutoGenerateCandidate {
	result := make([]groupAutoGenerateCandidate, 0, len(modelNames))
	seen := make(map[string]struct{}, len(modelNames))
	for _, modelName := range modelNames {
		name := strings.TrimSpace(modelName)
		if name == "" {
			continue
		}
		key := groupAutoGenerateModelKey(name, options)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		result = append(result, groupAutoGenerateCandidate{ModelName: name, ChannelID: channelID})
	}
	return result
}

func groupAutoGenerateGroupCandidates(candidates []groupAutoGenerateCandidate, options groupAutoGenerateOptions) []groupAutoGenerateModelBucket {
	byModel := make(map[string]*groupAutoGenerateModelBucket)
	for _, candidate := range candidates {
		key := groupAutoGenerateModelKey(candidate.ModelName, options)
		if key == "" || candidate.ChannelID == 0 {
			continue
		}
		bucket, ok := byModel[key]
		if !ok {
			association := groupAutoGenerateAssociationInfo(candidate.ModelName, options)
			bucket = &groupAutoGenerateModelBucket{
				ModelName:          association.DisplayName,
				preferredNameScore: association.Score,
			}
			byModel[key] = bucket
			groupAutoGenerateApplyAssociationInfo(bucket, association)
		} else {
			association := groupAutoGenerateAssociationInfo(candidate.ModelName, options)
			bucket.ModelName, bucket.preferredNameScore = groupAutoGeneratePreferredModelName(bucket.ModelName, bucket.preferredNameScore, association)
			groupAutoGenerateApplyAssociationInfo(bucket, association)
		}
		bucket.Aliases = append(bucket.Aliases, strings.TrimSpace(candidate.ModelName))
		bucket.Candidates = append(bucket.Candidates, candidate)
	}
	result := make([]groupAutoGenerateModelBucket, 0, len(byModel))
	for _, bucket := range byModel {
		sort.Slice(bucket.Candidates, func(i, j int) bool {
			if bucket.Candidates[i].ChannelID == bucket.Candidates[j].ChannelID {
				return bucket.Candidates[i].ModelName < bucket.Candidates[j].ModelName
			}
			return bucket.Candidates[i].ChannelID < bucket.Candidates[j].ChannelID
		})
		if bucket.scoreCount > 0 {
			bucket.MatchScore = (bucket.scoreTotal + bucket.scoreCount/2) / bucket.scoreCount
		}
		bucket.MatchStrategies = groupAutoGenerateStrategyKeysForDisplay(bucket.MatchStrategies)
		result = append(result, *bucket)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ModelName < result[j].ModelName })
	return result
}

func groupAutoGenerateExistingGroups(ctx context.Context, options groupAutoGenerateOptions) (map[string]*model.Group, error) {
	return groupAutoGenerateExistingGroupsWithDB(db.GetDB().WithContext(ctx), options)
}

func groupAutoGenerateExistingGroupsWithDB(conn *gorm.DB, options groupAutoGenerateOptions) (map[string]*model.Group, error) {
	var groups []model.Group
	if err := conn.Preload("Items").Order("id ASC").Find(&groups).Error; err != nil {
		return nil, err
	}
	result := make(map[string]*model.Group, len(groups))
	for i := range groups {
		key := groupAutoGenerateModelKey(groups[i].Name, options)
		if key == "" {
			continue
		}
		if _, exists := result[key]; exists {
			continue
		}
		group := groups[i]
		result[key] = &group
	}
	return result, nil
}

func groupAutoGeneratePreviewItem(bucket groupAutoGenerateModelBucket, existing *model.Group, options groupAutoGenerateOptions) model.GroupAutoGeneratePreviewItem {
	item := model.GroupAutoGeneratePreviewItem{
		ModelName:       bucket.ModelName,
		Aliases:         groupAutoGenerateAliasesForDisplay(bucket),
		CandidateCount:  len(bucket.Candidates),
		MatchScore:      bucket.MatchScore,
		MatchStrategies: groupAutoGenerateStrategyKeysForDisplay(bucket.MatchStrategies),
	}
	if existing == nil {
		item.WillCreate = len(bucket.Candidates) > 0
		item.MissingCandidateCount = len(bucket.Candidates)
		item.WillAddCount = len(bucket.Candidates)
		if len(bucket.Candidates) == 0 {
			item.SkippedReason = "no_candidates"
		}
		return item
	}
	missing := groupAutoGenerateMissingCandidates(*existing, bucket.Candidates, options)
	item.ExistingGroupID = existing.ID
	item.ExistingItemCount = len(existing.Items)
	item.MissingCandidateCount = len(missing)
	item.WillAddCount = len(missing)
	if len(missing) == 0 {
		item.SkippedReason = "already_complete"
	}
	return item
}

func groupAutoGenerateMissingCandidates(group model.Group, candidates []groupAutoGenerateCandidate, options groupAutoGenerateOptions) []groupAutoGenerateCandidate {
	existing := make(map[string]struct{}, len(group.Items))
	for _, item := range group.Items {
		key := groupAutoGenerateItemKey(item.ChannelID, item.ModelName, options)
		existing[key] = struct{}{}
	}
	result := make([]groupAutoGenerateCandidate, 0, len(candidates))
	seen := make(map[string]struct{}, len(candidates))
	for _, candidate := range candidates {
		key := groupAutoGenerateItemKey(candidate.ChannelID, candidate.ModelName, options)
		if _, ok := existing[key]; ok {
			continue
		}
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		result = append(result, candidate)
	}
	return result
}

func groupAutoGenerateCreateItems(tx *gorm.DB, groupID int, candidates []groupAutoGenerateCandidate, startPriority int) (int, error) {
	if len(candidates) == 0 {
		return 0, nil
	}
	items := make([]model.GroupItem, 0, len(candidates))
	priority := startPriority
	for _, candidate := range candidates {
		items = append(items, model.GroupItem{
			GroupID:   groupID,
			ChannelID: candidate.ChannelID,
			ModelName: candidate.ModelName,
			Priority:  priority,
			Weight:    1,
		})
		priority++
	}
	res := tx.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "group_id"}, {Name: "channel_id"}, {Name: "model_name"}},
		DoNothing: true,
	}).Create(&items)
	if res.Error != nil {
		return 0, fmt.Errorf("failed to create group items: %w", res.Error)
	}
	return int(res.RowsAffected), nil
}

func groupAutoGenerateNextPriority(items []model.GroupItem) int {
	next := 1
	for _, item := range items {
		if item.Priority >= next {
			next = item.Priority + 1
		}
	}
	return next
}

func groupAutoGenerateCandidateChannelIDs(candidates []groupAutoGenerateCandidate) []int {
	result := make([]int, 0, len(candidates))
	for _, candidate := range candidates {
		result = append(result, candidate.ChannelID)
	}
	return result
}

func groupAutoGenerateItemKey(channelID int, modelName string, options groupAutoGenerateOptions) string {
	return fmt.Sprintf("%d\x00%s", channelID, groupAutoGenerateModelKey(modelName, options))
}

func groupAutoGenerateModelKey(value string, options groupAutoGenerateOptions) string {
	return groupAutoGenerateAssociationInfo(value, options).ComparableKey
}

func groupAutoGenerateComparableName(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

type groupAutoGenerateAssociationInfoResult struct {
	DisplayName   string
	ComparableKey string
	Score         int
	Strategies    []string
}

func groupAutoGenerateAssociationInfo(value string, options groupAutoGenerateOptions) groupAutoGenerateAssociationInfoResult {
	original := strings.TrimSpace(value)
	if original == "" {
		return groupAutoGenerateAssociationInfoResult{}
	}
	name := original
	score := 100
	strategies := make([]string, 0, 4)
	if target, ok := groupAutoGenerateResolveManualAlias(name, options); ok {
		name = target
		score = 98
		strategies = append(strategies, "manual_alias")
	}
	name, namespaceStrategies := groupAutoGenerateStripConfiguredModelNamespace(name, options)
	for _, strategy := range namespaceStrategies {
		if groupAutoGenerateComparableName(name) == "" {
			continue
		}
		strategies = append(strategies, strategy)
		score -= groupAutoGenerateStrategyPenalty(strategy)
	}
	display := strings.TrimSpace(name)
	if display == "" {
		display = original
	}
	comparable := strings.TrimSpace(name)
	if options.NormalizeCase {
		lower := strings.ToLower(comparable)
		if lower != comparable {
			strategies = append(strategies, "normalize_case")
			score -= groupAutoGenerateStrategyPenalty("normalize_case")
		}
		comparable = lower
	}
	if options.NormalizeSeparators {
		normalized := groupAutoGenerateNormalizeModelSeparators(comparable)
		if normalized != comparable {
			strategies = append(strategies, "normalize_separators")
			score -= groupAutoGenerateStrategyPenalty("normalize_separators")
		}
		comparable = normalized
	}
	comparable = strings.TrimSpace(comparable)
	if comparable == "" {
		comparable = groupAutoGenerateComparableName(original)
	}
	if score < 60 {
		score = 60
	}
	if len(strategies) == 0 {
		strategies = []string{"exact"}
	}
	return groupAutoGenerateAssociationInfoResult{
		DisplayName:   display,
		ComparableKey: comparable,
		Score:         score,
		Strategies:    groupAutoGenerateStrategyKeysForDisplay(strategies),
	}
}

func groupAutoGeneratePreferredModelName(current string, currentScore int, candidate groupAutoGenerateAssociationInfoResult) (string, int) {
	display := candidate.DisplayName
	if strings.TrimSpace(current) == "" {
		return display, candidate.Score
	}
	if candidate.Score > currentScore {
		return display, candidate.Score
	}
	if candidate.Score < currentScore {
		return current, currentScore
	}
	currentHasNamespace := strings.Contains(current, "/")
	displayHasNamespace := strings.Contains(display, "/")
	if currentHasNamespace && !displayHasNamespace {
		return display, candidate.Score
	}
	if currentHasNamespace == displayHasNamespace {
		if len(display) < len(current) {
			return display, candidate.Score
		}
		if len(display) == len(current) && strings.ToLower(display) < strings.ToLower(current) {
			return display, candidate.Score
		}
	}
	return current, currentScore
}

func groupAutoGenerateApplyAssociationInfo(bucket *groupAutoGenerateModelBucket, association groupAutoGenerateAssociationInfoResult) {
	if bucket == nil || association.Score == 0 {
		return
	}
	bucket.scoreTotal += association.Score
	bucket.scoreCount++
	bucket.MatchStrategies = append(bucket.MatchStrategies, association.Strategies...)
}

func groupAutoGenerateAliasesForDisplay(bucket groupAutoGenerateModelBucket) []string {
	seen := make(map[string]string, len(bucket.Aliases))
	for _, alias := range bucket.Aliases {
		name := strings.TrimSpace(alias)
		if name == "" {
			continue
		}
		key := groupAutoGenerateComparableName(name)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = name
	}
	if len(seen) == 0 {
		return nil
	}
	aliases := make([]string, 0, len(seen))
	for _, alias := range seen {
		aliases = append(aliases, alias)
	}
	sort.Slice(aliases, func(i, j int) bool {
		return strings.ToLower(aliases[i]) < strings.ToLower(aliases[j])
	})
	if len(aliases) == 1 && groupAutoGenerateComparableName(aliases[0]) == groupAutoGenerateComparableName(bucket.ModelName) {
		return nil
	}
	return aliases
}

func groupAutoGenerateStripConfiguredModelNamespace(value string, options groupAutoGenerateOptions) (string, []string) {
	name := strings.TrimSpace(value)
	if name == "" {
		return "", nil
	}
	parts := strings.Split(name, "/")
	start := 0
	applied := make([]string, 0, 2)
	for start < len(parts)-1 {
		namespaceType := groupAutoGenerateKnownModelNamespace(parts[start])
		switch namespaceType {
		case "models":
			if !options.StripModelsNamespace {
				goto DONE
			}
			applied = append(applied, "strip_models_namespace")
		case "provider":
			if !options.StripProviderPrefix {
				goto DONE
			}
			applied = append(applied, "strip_provider_prefix")
		default:
			goto DONE
		}
		start++
	}
DONE:
	if start == 0 {
		return name, nil
	}
	rest := strings.TrimSpace(strings.Join(parts[start:], "/"))
	if rest == "" {
		return name, nil
	}
	return rest, groupAutoGenerateStrategyKeysForDisplay(applied)
}

func groupAutoGenerateKnownModelNamespace(value string) string {
	normalized := strings.ToLower(strings.TrimSpace(value))
	if normalized == "models" {
		return "models"
	}
	switch normalized {
	case "01-ai",
		"alibaba",
		"anthropic",
		"azure",
		"baichuan",
		"bedrock",
		"bytedance",
		"cohere",
		"deepseek",
		"doubao",
		"fireworks",
		"gemini",
		"glm",
		"google",
		"google-ai",
		"groq",
		"meta",
		"meta-llama",
		"mistral",
		"mistralai",
		"moonshot",
		"novita",
		"openai",
		"openai-compatible",
		"openrouter",
		"perplexity",
		"qwen",
		"siliconflow",
		"together",
		"vertex",
		"volcengine",
		"x-ai",
		"xai",
		"yi",
		"zhipu":
		return "provider"
	default:
		return ""
	}
}

func groupAutoGenerateNormalizeModelSeparators(value string) string {
	name := strings.ReplaceAll(value, "_", "-")
	name = strings.Join(strings.Fields(name), "-")
	for strings.Contains(name, "--") {
		name = strings.ReplaceAll(name, "--", "-")
	}
	return name
}

func groupAutoGenerateStrategyPenalty(strategy string) int {
	switch strategy {
	case "strip_provider_prefix":
		return 10
	case "strip_models_namespace":
		return 7
	case "normalize_separators":
		return 5
	case "normalize_case":
		return 3
	default:
		return 0
	}
}

func groupAutoGenerateStrategyKeysForDisplay(strategies []string) []string {
	if len(strategies) == 0 {
		return nil
	}
	order := map[string]int{
		"exact":                  0,
		"manual_alias":           1,
		"strip_provider_prefix":  2,
		"strip_models_namespace": 3,
		"normalize_case":         4,
		"normalize_separators":   5,
	}
	seen := make(map[string]struct{}, len(strategies))
	result := make([]string, 0, len(strategies))
	for _, strategy := range strategies {
		if strategy == "" {
			continue
		}
		if _, ok := seen[strategy]; ok {
			continue
		}
		seen[strategy] = struct{}{}
		result = append(result, strategy)
	}
	sort.Slice(result, func(i, j int) bool {
		left, leftOK := order[result[i]]
		right, rightOK := order[result[j]]
		if leftOK && rightOK && left != right {
			return left < right
		}
		if leftOK != rightOK {
			return leftOK
		}
		return result[i] < result[j]
	})
	return result
}

func groupAutoGenerateManualAliasMap(req *model.GroupAutoGenerateRequest, options groupAutoGenerateOptions) map[string]string {
	if req == nil || len(req.ManualAliases) == 0 {
		return nil
	}
	result := make(map[string]string, len(req.ManualAliases))
	for _, alias := range req.ManualAliases {
		key := groupAutoGenerateManualAliasKey(alias.Alias, options)
		target := strings.TrimSpace(alias.Target)
		if key == "" || target == "" {
			continue
		}
		result[key] = target
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

func groupAutoGenerateManualAliasKey(value string, options groupAutoGenerateOptions) string {
	name := strings.TrimSpace(value)
	if name == "" {
		return ""
	}
	name = strings.Join(strings.Fields(name), " ")
	if options.NormalizeCase {
		name = strings.ToLower(name)
	}
	return name
}

func groupAutoGenerateResolveManualAlias(value string, options groupAutoGenerateOptions) (string, bool) {
	if len(options.ManualAliases) == 0 {
		return "", false
	}
	key := groupAutoGenerateManualAliasKey(value, options)
	if key == "" {
		return "", false
	}
	target, ok := options.ManualAliases[key]
	return target, ok
}
