package op

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/bestruirui/octopus/internal/db"
	"github.com/bestruirui/octopus/internal/model"
	"github.com/bestruirui/octopus/internal/utils/xstrings"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type groupAutoGenerateCandidate struct {
	ModelName string
	ChannelID int
}

type groupAutoGenerateModelBucket struct {
	ModelName  string
	Candidates []groupAutoGenerateCandidate
}

func GroupAutoGeneratePreview(req *model.GroupAutoGenerateRequest, ctx context.Context) (*model.GroupAutoGeneratePreview, error) {
	buckets, totalModels, err := groupAutoGenerateBuckets(req, ctx)
	if err != nil {
		return nil, err
	}
	groups, err := groupAutoGenerateExistingGroups(ctx)
	if err != nil {
		return nil, err
	}
	items := make([]model.GroupAutoGeneratePreviewItem, 0, len(buckets))
	for _, bucket := range buckets {
		items = append(items, groupAutoGeneratePreviewItem(bucket, groups[groupAutoGenerateComparableName(bucket.ModelName)]))
	}
	return &model.GroupAutoGeneratePreview{
		TotalModels:    totalModels,
		SelectedModels: len(items),
		Items:          items,
	}, nil
}

func GroupAutoGenerate(req *model.GroupAutoGenerateRequest, ctx context.Context) (*model.GroupAutoGenerateResult, error) {
	buckets, totalModels, err := groupAutoGenerateBuckets(req, ctx)
	if err != nil {
		return nil, err
	}

	mode, firstTokenTimeout, sessionKeepTime, retryEnabled, maxRetries := groupAutoGenerateDefaults(req)
	result := &model.GroupAutoGenerateResult{
		TotalModels:    totalModels,
		SelectedModels: len(buckets),
		Items:          make([]model.GroupAutoGenerateResultItem, 0, len(buckets)),
	}
	affectedChannelIDs := make([]int, 0)

	err = db.GetDB().WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		groups, err := groupAutoGenerateExistingGroupsWithDB(tx)
		if err != nil {
			return err
		}

		for _, bucket := range buckets {
			item := model.GroupAutoGenerateResultItem{
				ModelName:      bucket.ModelName,
				CandidateCount: len(bucket.Candidates),
			}
			if len(bucket.Candidates) == 0 {
				item.SkippedReason = "no_candidates"
				result.SkippedGroups++
				result.Items = append(result.Items, item)
				continue
			}

			key := groupAutoGenerateComparableName(bucket.ModelName)
			existing := groups[key]
			if existing == nil {
				group := model.Group{
					Name:              bucket.ModelName,
					Mode:              mode,
					FirstTokenTimeOut: firstTokenTimeout,
					SessionKeepTime:   sessionKeepTime,
					RetryEnabled:      retryEnabled,
					MaxRetries:        maxRetries,
				}
				if err := tx.Create(&group).Error; err != nil {
					return fmt.Errorf("failed to create group %q: %w", bucket.ModelName, err)
				}
				created, err := groupAutoGenerateCreateItems(tx, group.ID, bucket.Candidates, 1)
				if err != nil {
					return err
				}
				item.GroupID = group.ID
				item.Created = true
				item.AddedItems = created
				result.CreatedGroups++
				result.AddedItems += created
				groups[key] = &model.Group{ID: group.ID, Name: group.Name, Items: nil}
				affectedChannelIDs = append(affectedChannelIDs, groupAutoGenerateCandidateChannelIDs(bucket.Candidates)...)
				result.Items = append(result.Items, item)
				continue
			}

			missing := groupAutoGenerateMissingCandidates(*existing, bucket.Candidates)
			item.GroupID = existing.ID
			if len(missing) == 0 {
				item.SkippedReason = "already_complete"
				result.SkippedGroups++
				result.Items = append(result.Items, item)
				continue
			}

			nextPriority := groupAutoGenerateNextPriority(existing.Items)
			created, err := groupAutoGenerateCreateItems(tx, existing.ID, missing, nextPriority)
			if err != nil {
				return err
			}
			item.AddedItems = created
			result.UpdatedGroups++
			result.AddedItems += created
			affectedChannelIDs = append(affectedChannelIDs, groupAutoGenerateCandidateChannelIDs(missing)...)
			result.Items = append(result.Items, item)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	if err := groupRefreshCache(ctx); err != nil {
		return nil, err
	}
	resetBalancerStateForChannels(affectedChannelIDs...)
	return result, nil
}

func groupAutoGenerateDefaults(req *model.GroupAutoGenerateRequest) (model.GroupMode, int, int, bool, int) {
	mode := model.GroupModeRoundRobin
	firstTokenTimeout := 0
	sessionKeepTime := 0
	retryEnabled := false
	maxRetries := 3
	if req == nil {
		return mode, firstTokenTimeout, sessionKeepTime, retryEnabled, maxRetries
	}
	if req.Mode != nil {
		switch *req.Mode {
		case model.GroupModeRoundRobin, model.GroupModeRandom, model.GroupModeFailover, model.GroupModeWeighted:
			mode = *req.Mode
		}
	}
	if req.FirstTokenTimeOut > 0 {
		firstTokenTimeout = req.FirstTokenTimeOut
	}
	if req.SessionKeepTime > 0 {
		sessionKeepTime = req.SessionKeepTime
	}
	retryEnabled = req.RetryEnabled
	if req.MaxRetries > 0 {
		maxRetries = req.MaxRetries
	}
	return mode, firstTokenTimeout, sessionKeepTime, retryEnabled, maxRetries
}

func groupAutoGenerateBuckets(req *model.GroupAutoGenerateRequest, ctx context.Context) ([]groupAutoGenerateModelBucket, int, error) {
	candidates, err := groupAutoGenerateCandidates(ctx)
	if err != nil {
		return nil, 0, err
	}
	allBuckets := groupAutoGenerateGroupCandidates(candidates)
	selected := groupAutoGenerateSelection(req)
	if len(selected) == 0 {
		return allBuckets, len(allBuckets), nil
	}
	result := make([]groupAutoGenerateModelBucket, 0, len(selected))
	for _, bucket := range allBuckets {
		if _, ok := selected[groupAutoGenerateComparableName(bucket.ModelName)]; ok {
			result = append(result, bucket)
		}
	}
	return result, len(allBuckets), nil
}

func groupAutoGenerateSelection(req *model.GroupAutoGenerateRequest) map[string]struct{} {
	if req == nil || req.All || len(req.ModelNames) == 0 {
		return nil
	}
	selected := make(map[string]struct{}, len(req.ModelNames))
	for _, name := range req.ModelNames {
		if key := groupAutoGenerateComparableName(name); key != "" {
			selected[key] = struct{}{}
		}
	}
	return selected
}

func groupAutoGenerateCandidates(ctx context.Context) ([]groupAutoGenerateCandidate, error) {
	var channels []model.Channel
	if err := db.GetDB().WithContext(ctx).Order("id ASC").Find(&channels).Error; err != nil {
		return nil, err
	}
	channelIDs := make([]int, 0, len(channels))
	for _, channel := range channels {
		channelIDs = append(channelIDs, channel.ID)
	}
	bindings, err := SiteChannelBindingMapByChannelIDs(channelIDs, ctx)
	if err != nil {
		return nil, err
	}

	result := make([]groupAutoGenerateCandidate, 0)
	for _, channel := range channels {
		if channel.ID == 0 || !channel.Enabled {
			continue
		}
		if binding, ok := bindings[channel.ID]; ok {
			modelNames, err := groupAutoGenerateProjectedModelNames(ctx, channel, binding)
			if err != nil {
				return nil, err
			}
			result = append(result, groupAutoGenerateCandidatesForChannel(channel.ID, modelNames)...)
			continue
		}
		modelNames := xstrings.SplitTrimCompact(",", channel.Model, channel.CustomModel)
		result = append(result, groupAutoGenerateCandidatesForChannel(channel.ID, modelNames)...)
	}
	return result, nil
}

func groupAutoGenerateProjectedModelNames(ctx context.Context, channel model.Channel, binding model.SiteChannelBinding) ([]string, error) {
	var rows []model.SiteModel
	if err := db.GetDB().WithContext(ctx).
		Where("site_account_id = ? AND disabled = ?", binding.SiteAccountID, false).
		Find(&rows).Error; err != nil {
		return nil, err
	}
	baseGroupKey, _ := model.ParseSiteChannelBindingKey(binding.GroupKey)
	routeType := model.SiteModelRouteTypeFromOutboundType(channel.Type)

	names := make([]string, 0, len(rows))
	for _, row := range rows {
		name := strings.TrimSpace(row.ModelName)
		if name == "" {
			continue
		}
		if model.NormalizeSiteGroupKey(row.GroupKey) != baseGroupKey {
			continue
		}
		if !groupAutoGenerateSiteModelBelongsToGroup(row, baseGroupKey) {
			continue
		}
		if model.NormalizeSiteModelRouteType(row.RouteType) != routeType {
			continue
		}
		names = append(names, name)
	}
	return names, nil
}

func groupAutoGenerateSiteModelBelongsToGroup(item model.SiteModel, groupKey string) bool {
	metadata, ok := model.ParseSiteModelRouteMetadata(item.RouteRawPayload)
	if !ok || len(metadata.EnableGroups) == 0 {
		return true
	}
	targetGroupKey := model.NormalizeSiteGroupKey(groupKey)
	for _, explicitGroupKey := range metadata.EnableGroups {
		if model.NormalizeSiteGroupKey(explicitGroupKey) == targetGroupKey {
			return true
		}
	}
	return false
}

func groupAutoGenerateCandidatesForChannel(channelID int, modelNames []string) []groupAutoGenerateCandidate {
	result := make([]groupAutoGenerateCandidate, 0, len(modelNames))
	seen := make(map[string]struct{}, len(modelNames))
	for _, modelName := range modelNames {
		name := strings.TrimSpace(modelName)
		if name == "" {
			continue
		}
		key := groupAutoGenerateComparableName(name)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		result = append(result, groupAutoGenerateCandidate{ModelName: name, ChannelID: channelID})
	}
	return result
}

func groupAutoGenerateGroupCandidates(candidates []groupAutoGenerateCandidate) []groupAutoGenerateModelBucket {
	byModel := make(map[string]*groupAutoGenerateModelBucket)
	for _, candidate := range candidates {
		key := groupAutoGenerateComparableName(candidate.ModelName)
		if key == "" || candidate.ChannelID == 0 {
			continue
		}
		bucket, ok := byModel[key]
		if !ok {
			bucket = &groupAutoGenerateModelBucket{ModelName: strings.TrimSpace(candidate.ModelName)}
			byModel[key] = bucket
		}
		bucket.Candidates = append(bucket.Candidates, candidate)
	}
	result := make([]groupAutoGenerateModelBucket, 0, len(byModel))
	for _, bucket := range byModel {
		sort.Slice(bucket.Candidates, func(i, j int) bool {
			if bucket.Candidates[i].ChannelID == bucket.Candidates[j].ChannelID {
				return bucket.Candidates[i].ModelName < bucket.Candidates[j].ModelName
			}
			return bucket.Candidates[i].ChannelID < bucket.Candidates[j].ChannelID
		})
		result = append(result, *bucket)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ModelName < result[j].ModelName })
	return result
}

func groupAutoGenerateExistingGroups(ctx context.Context) (map[string]*model.Group, error) {
	return groupAutoGenerateExistingGroupsWithDB(db.GetDB().WithContext(ctx))
}

func groupAutoGenerateExistingGroupsWithDB(conn *gorm.DB) (map[string]*model.Group, error) {
	var groups []model.Group
	if err := conn.Preload("Items").Find(&groups).Error; err != nil {
		return nil, err
	}
	result := make(map[string]*model.Group, len(groups))
	for i := range groups {
		key := groupAutoGenerateComparableName(groups[i].Name)
		if key == "" {
			continue
		}
		group := groups[i]
		result[key] = &group
	}
	return result, nil
}

func groupAutoGeneratePreviewItem(bucket groupAutoGenerateModelBucket, existing *model.Group) model.GroupAutoGeneratePreviewItem {
	item := model.GroupAutoGeneratePreviewItem{
		ModelName:      bucket.ModelName,
		CandidateCount: len(bucket.Candidates),
	}
	if existing == nil {
		item.WillCreate = len(bucket.Candidates) > 0
		item.MissingCandidateCount = len(bucket.Candidates)
		item.WillAddCount = len(bucket.Candidates)
		if len(bucket.Candidates) == 0 {
			item.SkippedReason = "no_candidates"
		}
		return item
	}
	missing := groupAutoGenerateMissingCandidates(*existing, bucket.Candidates)
	item.ExistingGroupID = existing.ID
	item.ExistingItemCount = len(existing.Items)
	item.MissingCandidateCount = len(missing)
	item.WillAddCount = len(missing)
	if len(missing) == 0 {
		item.SkippedReason = "already_complete"
	}
	return item
}

func groupAutoGenerateMissingCandidates(group model.Group, candidates []groupAutoGenerateCandidate) []groupAutoGenerateCandidate {
	existing := make(map[string]struct{}, len(group.Items))
	for _, item := range group.Items {
		key := groupAutoGenerateItemKey(item.ChannelID, item.ModelName)
		existing[key] = struct{}{}
	}
	result := make([]groupAutoGenerateCandidate, 0, len(candidates))
	seen := make(map[string]struct{}, len(candidates))
	for _, candidate := range candidates {
		key := groupAutoGenerateItemKey(candidate.ChannelID, candidate.ModelName)
		if _, ok := existing[key]; ok {
			continue
		}
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		result = append(result, candidate)
	}
	return result
}

func groupAutoGenerateCreateItems(tx *gorm.DB, groupID int, candidates []groupAutoGenerateCandidate, startPriority int) (int, error) {
	if len(candidates) == 0 {
		return 0, nil
	}
	items := make([]model.GroupItem, 0, len(candidates))
	priority := startPriority
	for _, candidate := range candidates {
		items = append(items, model.GroupItem{
			GroupID:   groupID,
			ChannelID: candidate.ChannelID,
			ModelName: candidate.ModelName,
			Priority:  priority,
			Weight:    1,
		})
		priority++
	}
	res := tx.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "group_id"}, {Name: "channel_id"}, {Name: "model_name"}},
		DoNothing: true,
	}).Create(&items)
	if res.Error != nil {
		return 0, fmt.Errorf("failed to create group items: %w", res.Error)
	}
	return int(res.RowsAffected), nil
}

func groupAutoGenerateNextPriority(items []model.GroupItem) int {
	next := 1
	for _, item := range items {
		if item.Priority >= next {
			next = item.Priority + 1
		}
	}
	return next
}

func groupAutoGenerateCandidateChannelIDs(candidates []groupAutoGenerateCandidate) []int {
	result := make([]int, 0, len(candidates))
	for _, candidate := range candidates {
		result = append(result, candidate.ChannelID)
	}
	return result
}

func groupAutoGenerateItemKey(channelID int, modelName string) string {
	return fmt.Sprintf("%d\x00%s", channelID, groupAutoGenerateComparableName(modelName))
}

func groupAutoGenerateComparableName(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}
